import parser from "esprima";
import castl from "@sapiens/spjs/castl/castl";
import luamin from "luamin";
import * as babel from "@babel/standalone";

export function compileJavascript(source: string, filename: string) {
  const transformed = babel.transform(source, {
    presets: ["env", "typescript"],
    filename: filename,
  })?.code;
  if (!transformed)
    throw new Error("Could not convert Typescript to JavaScript");
  const ast = parser.parse(transformed, { tolerant: true });
  const codeStrings = [];

  // At necessary runtime includes
  codeStrings.push(`local _ENV = mjrequire \"castl/runtime\";`);
  codeStrings.push(`_ENV.__use(_ENV);`);
  codeStrings.push(`exports = {};`);

  codeStrings.push(castl.compileAST(ast, {}).compiled);

  codeStrings.push(`return exports["default"];`);

  const code = codeStrings.join("\n");
  const minifiedLua = `-- Generated by the Sapiens Web Builder using @sapiens/spjs\n${luamin.minify(
    code
  )}`;
  return minifiedLua;
}
